/**
 * Stable primitive aliases used across the extracted design-system model.
 */
export type TokenId = string;
export type PixelValue = number;
export type ColorValue = string;

/**
 * Enumerates the supported token categories used by Figma-style foundations.
 */
export type TokenCategory = "color" | "typography" | "effect";

/**
 * Describes where a color token is intended to be applied.
 */
export type ColorTokenRole = "fill" | "stroke" | "text";

/**
 * Shared metadata carried by all extracted tokens.
 */
export interface TokenBase {
  /**
   * Unique identifier generated by the extractor.
   */
  id: TokenId;
  /**
   * Human-readable token name, typically slash-delimited.
   * Example: `button/primary/fill`.
   */
  name: string;
  /**
   * High-level token category.
   */
  category: TokenCategory;
  /**
   * Original source for debugging and traceability.
   * Example: CSS variable, computed style, or DOM selector.
   */
  source: string;
  /**
   * Optional description generated during extraction.
   */
  description?: string;
}

/**
 * Represents a color token that can be applied as a fill, stroke, or text color.
 */
export interface ColorToken extends TokenBase {
  /**
   * Discriminator for color tokens.
   */
  category: "color";
  /**
   * The semantic usage of the token in the UI.
   */
  role: ColorTokenRole;
  /**
   * The resolved CSS color value.
   * Example: `#2563eb`, `rgba(37, 99, 235, 1)`.
   */
  value: ColorValue;
  /**
   * Optional alpha channel normalized from 0 to 1.
   */
  opacity?: number;
}

/**
 * Enumerates the supported font-weight values for extracted typography.
 */
export type FontWeight =
  | 100
  | 200
  | 300
  | 400
  | 500
  | 600
  | 700
  | 800
  | 900;

/**
 * Represents a typography token aligned with Figma text styles.
 */
export interface TypographyToken extends TokenBase {
  /**
   * Discriminator for typography tokens.
   */
  category: "typography";
  /**
   * Primary font family applied to the text style.
   */
  fontFamily: string;
  /**
   * Font size in pixels.
   */
  fontSize: PixelValue;
  /**
   * Numeric font-weight value.
   */
  fontWeight: FontWeight;
  /**
   * Line height in pixels.
   */
  lineHeight: PixelValue;
  /**
   * Letter spacing in pixels.
   */
  letterSpacing: PixelValue;
  /**
   * Optional text transform extracted from CSS.
   */
  textTransform?: "none" | "uppercase" | "lowercase" | "capitalize";
}

/**
 * Enumerates supported visual effect styles.
 */
export type EffectStyle = "drop-shadow" | "inner-shadow" | "layer-blur" | "background-blur";

/**
 * Defines an offset pair in pixels.
 */
export interface Offset {
  /**
   * Horizontal offset.
   */
  x: PixelValue;
  /**
   * Vertical offset.
   */
  y: PixelValue;
}

/**
 * Represents an effect token mapped from CSS shadows or blur values.
 */
export interface EffectToken extends TokenBase {
  /**
   * Discriminator for effect tokens.
   */
  category: "effect";
  /**
   * The extracted effect style.
   */
  style: EffectStyle;
  /**
   * Shadow color when the effect represents a shadow.
   */
  color?: ColorValue;
  /**
   * Shadow offset in pixels.
   */
  offset?: Offset;
  /**
   * Blur radius in pixels.
   */
  blurRadius: PixelValue;
  /**
   * Spread radius in pixels for shadow-based effects.
   */
  spreadRadius?: PixelValue;
}

/**
 * Aggregates the full foundation token set extracted from the DOM.
 */
export interface DesignTokens {
  /**
   * Extracted color styles.
   */
  colors: ColorToken[];
  /**
   * Extracted typography styles.
   */
  typography: TypographyToken[];
  /**
   * Extracted effect styles.
   */
  effects: EffectToken[];
}

/**
 * Enumerates supported auto-layout directions.
 */
export type AutoLayoutDirection = "horizontal" | "vertical";

/**
 * Maps Figma cross-axis and main-axis alignment keywords.
 */
export type AutoLayoutAlignment =
  | "start"
  | "center"
  | "end"
  | "space-between"
  | "space-around"
  | "space-evenly"
  | "stretch";

/**
 * Defines a four-sided spacing contract in pixels.
 */
export interface Spacing {
  /**
   * Top padding or inset.
   */
  top: PixelValue;
  /**
   * Right padding or inset.
   */
  right: PixelValue;
  /**
   * Bottom padding or inset.
   */
  bottom: PixelValue;
  /**
   * Left padding or inset.
   */
  left: PixelValue;
}

/**
 * Represents auto-layout behavior inferred from CSS flexbox or grid-like layout rules.
 */
export interface AutoLayout {
  /**
   * Primary stacking direction for child elements.
   */
  direction: AutoLayoutDirection;
  /**
   * Gap between child items in pixels.
   */
  gap: PixelValue;
  /**
   * Internal padding for the container.
   */
  padding: Spacing;
  /**
   * Main-axis alignment of child elements.
   */
  primaryAlignment: AutoLayoutAlignment;
  /**
   * Cross-axis alignment of child elements.
   */
  counterAlignment: AutoLayoutAlignment;
  /**
   * Whether children should wrap onto additional lines.
   */
  wrap?: boolean;
}

/**
 * Enumerates the component categories currently recognized by the extractor.
 */
export type ComponentType =
  | "Button"
  | "Card"
  | "Input"
  | "Badge"
  | "Modal"
  | "Navigation"
  | "Unknown";

/**
 * Shared structural metadata for any extracted component.
 */
export interface ComponentBase {
  /**
   * Stable component identifier.
   */
  id: string;
  /**
   * User-facing component name.
   */
  name: string;
  /**
   * Canonical component class inferred from the DOM pattern.
   */
  type: ComponentType;
  /**
   * Source selector or DOM path used during extraction.
   */
  source: string;
  /**
   * Optional freeform notes produced by the parser.
   */
  description?: string;
}

/**
 * Variant axes aligned with common Figma component property groups.
 */
export type ComponentStyleVariant = "fill" | "outline" | "ghost";
export type ComponentStateVariant =
  | "default"
  | "hover"
  | "focused"
  | "active"
  | "disabled";
export type ComponentSizeVariant = "sm" | "md" | "lg";

/**
 * Describes a normalized component variant selection.
 */
export interface ComponentVariants {
  /**
   * Visual treatment of the component.
   */
  style: ComponentStyleVariant;
  /**
   * Interaction or lifecycle state.
   */
  state: ComponentStateVariant;
  /**
   * Size bucket used by the component.
   */
  size: ComponentSizeVariant;
}

/**
 * References the token IDs applied to a component instance.
 */
export interface AppliedTokenSet {
  /**
   * Fill tokens applied to the component container.
   */
  fills: TokenId[];
  /**
   * Stroke tokens applied to borders or outlines.
   */
  strokes: TokenId[];
  /**
   * Text color tokens applied within the component.
   */
  text: TokenId[];
  /**
   * Typography tokens applied to textual content.
   */
  typography: TokenId[];
  /**
   * Visual effects applied to the component.
   */
  effects: TokenId[];
}

/**
 * Final extracted component contract consumed by the parser and extension UI.
 */
export interface ExtractedComponent extends ComponentBase {
  /**
   * Variant axes that define this component instance.
   */
  variants: ComponentVariants;
  /**
   * Foundation tokens applied to the component.
   */
  tokens: AppliedTokenSet;
  /**
   * Auto-layout rules inferred from the DOM structure.
   */
  autoLayout?: AutoLayout;
  /**
   * Corner radius in pixels extracted from the DOM element.
   */
  cornerRadius?: PixelValue;
  /**
   * Visible text content of the component, if present.
   */
  textContent?: string;
  /**
   * Nested child components extracted from the same subtree.
   */
  children?: ExtractedComponent[];
}

/**
 * Aggregates both foundation tokens and inferred components from a single extraction pass.
 */
export interface ExtractionResult {
  /**
   * Extracted foundation tokens.
   */
  tokens: DesignTokens;
  /**
   * Extracted reusable component patterns.
   */
  components: ExtractedComponent[];
}
